theme: jekyll-theme-dinky
title: "Workshop on Life-long Learning for Spoken Language Systems"
description: "This workshop covers challenges related to continual improvement of Spoken Language Systems such as conversational AI agents."
show_downloads: false
google_analytics: UA-175333451-1


